<h1>NUMPY basics

* This is to import numpy

In [1]:
import numpy as np

* <h2>creating a rank 1 ndarray with a

In [4]:
an_array=np.array([3,33,333])
print(an_array)

[  3  33 333]


* knowing the type 

In [5]:
type(an_array)

numpy.ndarray

* knowing the shape and dimension of an array

In [7]:
an_array.shape

(3,)

* indexing an array

In [9]:
print(an_array[0:1])

[3]


* replacing elements in an ndarray

In [10]:
an_array[0]=4

* more examples of indexing

In [11]:
an_array

array([  4,  33, 333])

In [12]:
an_array[2]

333

* creating a rank 2 ndarray

In [13]:
second=np.array([[42,43,44],[52,53,54]])

In [14]:
print(second)

[[42 43 44]
 [52 53 54]]


In [15]:
second.shape

(2, 3)

In [3]:
import numpy as np

* creating an ndarray with the dimensions with .full function and with the same values

In [5]:
test=np.full((2,3),4)
print(test)

[[4 4 4]
 [4 4 4]]


* .zeroes function

In [10]:
zero=np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


* eye function gives an array of 0 and 1s

In [12]:
binary=np.eye(2,4)
print(binary)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


* ones function gives an array of 1s

In [15]:
One=np.ones(3)
print(One)

[1. 1. 1.]


In [2]:
import numpy as np

In [4]:
ran=np.random.random((2,3))
print(ran)

[[0.34406505 0.02867681 0.04309167]
 [0.51093927 0.39185307 0.20325894]]


In [18]:
import numpy as np

In [19]:
print(ran)

[[0.82019885 0.42180208 0.81857033]
 [0.18366009 0.37904497 0.17012232]]


In [20]:
slice_ran=ran[0:2,0:2]
print(slice_ran)

[[0.82019885 0.42180208]
 [0.18366009 0.37904497]]


In [21]:
slice_ran[0]

array([0.82019885, 0.42180208])

In [1]:
import numpy as np

In [5]:
group=np.array([[3,4,5],[6,7,8],[9,10,11]])
print(group)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


* boolean indexing and conditionals

In [9]:
groupA=(group>7)
print([groupA])

[array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])]


In [7]:
groupA=([groupA])
print(groupA)

[array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])]


In [8]:
print(groupA)

[array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])]


* taking values from an ndarray through conditionals  and creating a new array

In [10]:
groupA=(group[groupA])
print(groupA)

[ 8  9 10 11]


* excercises

In [18]:
groupC=([group])
print(groupC)

[array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])]


* types of data within ndarrays can be determined with d.type

In [28]:
print(groupA.dtype)

int32


* Basic arithmatic function with ndarrays

In [30]:
Marks=np.array([[98.0,99.5,90.0],[55.5,60.0,57.0],[22.5,30.0,40.0]])
hours=np.array([[8.0,9.5,9.0],[5.5,6.0,5.0],[2.5,3.0,4.0]])


In [31]:
print(Marks)
print(hours)

[[98.  99.5 90. ]
 [55.5 60.  57. ]
 [22.5 30.  40. ]]
[[8.  9.5 9. ]
 [5.5 6.  5. ]
 [2.5 3.  4. ]]


In [35]:
Marks_per_hour=Marks/hours
print(Marks_per_hour)

[[12.25       10.47368421 10.        ]
 [10.09090909 10.         11.4       ]
 [ 9.         10.         10.        ]]


* basic statistical functions

In [3]:
import numpy as np

In [7]:
stat1=np.array([[34,45,50,48],[29,36,47,15]])
stat2=np.array([[40,51,76,65],[55,65,34,28]])
print(stat1)
print(stat2)

[[34 45 50 48]
 [29 36 47 15]]
[[40 51 76 65]
 [55 65 34 28]]


* the arithmatic mean of an ndarray can be found using .mean() function [we can specify what data type value can be if we want]

In [10]:
print(int(stat1.mean()))

38


*we can also specify one axis of mean which will produce means of each row in an ndarray

In [12]:
print(stat2.mean(axis=1))

[58.  45.5]


* if we pass the arguement of axis=0 in the maen function then we get means of the coloumns

In [16]:
print(stat1.mean(axis=0))

[31.5 40.5 48.5 31.5]


*the sum of an array can be calculated with the .sum() function

In [17]:
print(stat1.sum())

304


* Similarly we can know the sum of the rows and columns by passing in the axis=1 and axis=0 arguements respectively

In [21]:
print(stat1.sum(axis=1),stat1.sum(axis=0))

[177 127] [63 81 97 63]


* we can find the median of the rows like passintg in the axis=1 argument in the .median() function

In [23]:
print(np.median(stat1,axis=1))

[46.5 32.5]


* we can find the median of the columns like passintg in the axis=0 argument in the .median() function

In [24]:
print(np.median(stat1,axis=0))

[31.5 40.5 48.5 31.5]


In [48]:
elo=np.random.randn(10)
print(elo)

[-0.19598143 -0.20494701  1.56607374  1.22340678  0.36634293  0.61082685
 -1.41682495  0.43437099  1.47505818 -0.12044836]


In [49]:
print(elo)

[-0.19598143 -0.20494701  1.56607374  1.22340678  0.36634293  0.61082685
 -1.41682495  0.43437099  1.47505818 -0.12044836]


* passing the ndarray name as an argument sorts the array from lowest to highest order

In [54]:
melo=sorted(elo)
print(melo)

[-1.4168249542322537, -0.20494701364522747, -0.19598143266391896, -0.12044835944172731, 0.36634292745071567, 0.43437099119899225, 0.6108268479189063, 1.2234067755531821, 1.4750581763553514, 1.566073739524301]


* the unique method returns the unique values in an array

In [55]:
only=np.array([[2,3,4,3,5]])

In [58]:
print(np.unique(only))

[2 3 4 5]


* there are other methods related to sets which are intersect, union , difference

In [5]:
jinish=np.array(['Kheta','balish','lep'])
potro=np.array(['balish','lep','toshok'])

In [6]:
print(np.intersect1d(jinish, potro))

['balish' 'lep']


In [7]:
print(np.union1d(jinish, potro))

['Kheta' 'balish' 'lep' 'toshok']


In [8]:
print(np.setdiff1d(jinish, potro))

['Kheta']


In [10]:
print(np.in1d(jinish, potro))

[False  True  True]


* Broadcasting 

In [14]:
k1=np.zeros((2,4))
k2=np.array([2,3,4,5])
print(k1)
print(k2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[2 3 4 5]


In [15]:
k3=k1+k2
print(k3)

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]]


* we can transpose an array using .T

In [16]:
k4=k3.T
print(k4)

[[2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]]


In [18]:
k4+2

array([[4., 4.],
       [5., 5.],
       [6., 6.],
       [7., 7.]])